# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                  : "minimal-mistakes-jekyll"
#remote_theme             : "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "neon" # "dark" #"dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "DRI374 LIVE PINBALL STREAMING"
title_separator          : "-"
subtitle                 : "Raccoon City Pinball and Arcade" # site tagline that appears below site title in masthead
name                     : "Michael Mattsson"
description              : "Michael 'DRI374' Mattsson is a pinball and arcade gamer who stream games on Twitch, mainly from his home arcade, Raccoon City Pinball"
url                      : "https://dri374.live" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "datamattsson/dri374.live" # GitHub username/repo-name e.g. "datamattsson/dri374.live"
teaser                   : "/assets/images/teaser-600x400.png"
logo                     : "/assets/images/masthead-88x88.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "DRI374 STREAMING"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
enable_copy_code_button  : true #, false (default)
copyright                : # "copyright" name, defaults to site.title
copyright_url            : # "copyright" URL, defaults to site.url
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "dri374" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 for enabled, 0 for disabled (default)
    input_position       : # "top", "bottom" # The comment input box will be placed above or below the comments
    emit_metadata        : # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    lang                 : # "en" (default)
    lazy                 : # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
facebook:
  username               : "dri374"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/og-frontpage-1200x630.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : "DRI374: Raccoon City Pinball and Arcade" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
  - "https://twitch.tv/dri374"
  - "https://youtube.com/dri374"
  - "https://bsky.app/profile/dri374.live"
  - "https://instagram.com/dri374"
  - "https://tiktok.com/@dri.374"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-7WBJJ4DWM4"
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "Michael Mattsson a.k.a DRI374"
  avatar           : "/assets/images/bio-160x160.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I collect and look at pinball machines. Sometimes I play them too."
  location         : "Santa Cruz, CA"
  email            : 
  links:
  - label: "linktr.ee/dri374"
    icon: "fa-solid fa-link"
    url: "https://linktr.ee/dri374"

# Site Footer
footer:
  links:
    - label: "Watch LIVE on Twitch"
      icon: "fa-brands fa-twitch"
      url: "https://twitch.tv/dri374"
    - label: "Check VODs on YouTube"
      #icon: "fab fa-fw fa-youtube-square"
      icon: "fa-brands fa-youtube" 
      url: "https://youtube.com/dri374"
    - label: "Follow on Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/dri374"
    - label: "Like on Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://facebook.com/dri374"
    - label: "Skeet at on BlueSky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/dri374.live"
    - label: "FlipFlop on TikTok"
      icon: "fa-brands fa-tiktok"
      url: "https://tiktok.com/@dri.374"
    - label: "Swag up on SWAG.DRI374.LIVE"
      icon: "fa-solid fa-shirt"
      url: "https://swag.dri374.live"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG.md
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE.md
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - Makefile
  - templates
  - tmp
  - TODO
  - FORMATTING.md
  - CNAME
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /blog/tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
